#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libao
Version  : 1.2.2
Release  : 3
URL      : https://github.com/xiph/libao/archive/20dc8ed9fa4605f5c25e7496ede42e8ba6468225/1.2.2.tar.gz
Source0  : https://github.com/xiph/libao/archive/20dc8ed9fa4605f5c25e7496ede42e8ba6468225/1.2.2.tar.gz
Summary  : Cross Platform Audio Output Library Development
Group    : Development/Tools
License  : GPL-2.0
Requires: libao-lib = %{version}-%{release}
Requires: libao-license = %{version}-%{release}
Requires: libao-man = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : libXau-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(x11)
BuildRequires : sndio-dev

%description
Libao is a cross-platform audio output library.  It currently supports
ESD, aRts, ALSA, OSS, *BSD and Solaris.

This package provides plug-ins for OSS, ESD, aRts, and ALSA (0.9).  You will
need to install the supporting libraries for any plug-ins you want to use
in order for them to work.

Available rpmbuild rebuild options :
--with : alsa
--without : esd arts

%package dev
Summary: dev components for the libao package.
Group: Development
Requires: libao-lib = %{version}-%{release}
Provides: libao-devel = %{version}-%{release}
Requires: libao = %{version}-%{release}

%description dev
dev components for the libao package.


%package doc
Summary: doc components for the libao package.
Group: Documentation
Requires: libao-man = %{version}-%{release}

%description doc
doc components for the libao package.


%package lib
Summary: lib components for the libao package.
Group: Libraries
Requires: libao-license = %{version}-%{release}

%description lib
lib components for the libao package.


%package license
Summary: license components for the libao package.
Group: Default

%description license
license components for the libao package.


%package man
Summary: man components for the libao package.
Group: Default

%description man
man components for the libao package.


%prep
%setup -q -n libao-20dc8ed9fa4605f5c25e7496ede42e8ba6468225
cd %{_builddir}/libao-20dc8ed9fa4605f5c25e7496ede42e8ba6468225

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1574062086
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1574062086
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libao
cp %{_builddir}/libao-20dc8ed9fa4605f5c25e7496ede42e8ba6468225/COPYING %{buildroot}/usr/share/package-licenses/libao/dfac199a7539a404407098a2541b9482279f690d
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/ckport/db/libao.ckport

%files dev
%defattr(-,root,root,-)
/usr/include/ao/ao.h
/usr/include/ao/os_types.h
/usr/include/ao/plugin.h
/usr/lib64/libao.so
/usr/lib64/pkgconfig/ao.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libao/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/ao/plugins-4/libalsa.so
/usr/lib64/ao/plugins-4/liboss.so
/usr/lib64/ao/plugins-4/libpulse.so
/usr/lib64/ao/plugins-4/libsndio.so
/usr/lib64/libao.so.4
/usr/lib64/libao.so.4.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libao/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/libao.conf.5
